# Practical 5
    Name : Yash Brahmkshatriya
    Roll No. : 18BCE029
    Batch : A2

In [5]:
import numpy as np
from sklearn import neighbors, datasets, metrics

### Loading Dataset 

In [6]:
# Loading Irish Dataset
X, y = datasets.load_iris(return_X_y = True)

# Slicing even index rows to train
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

# Slicing odd index rows to test
X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

### KNN using K = 3 

In [7]:
# Value of K (No. of nearest neighbors to be considered)
n_neighbors = 3

# normal KNN using frequency
weights = 'uniform'
# if weights = 'distance', then it would be distance weighted KNN

clf = neighbors.KNeighborsClassifier(n_neighbors=3,weights='uniform')
# 3rd argument is metric ,default is 'minkowski'
# 4th arg is p(power of minkowski distance), default =2 ,which is eq. to eucledian

clf.fit(X_train,y_train)

prediction = clf.predict(X_test)

print('----------PREDICTIONS----------')
print(prediction)
print('-------------------------------')

print('Accuracy = ',metrics.accuracy_score(y_test, prediction, normalize=True))
print('\nConfusion Matrix = \n',metrics.confusion_matrix(y_test, prediction, normalize=None))

----------PREDICTIONS----------
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
-------------------------------
Accuracy =  0.96

Confusion Matrix = 
 [[25  0  0]
 [ 0 23  2]
 [ 0  1 24]]


### KNN using K = 5

In [8]:
# Value of K (No. of nearest neighbors to be considered)
n_neighbors = 5

# normal KNN using frequency
weights = 'uniform'
# if weights = 'distance', then it would be distance weighted KNN

clf = neighbors.KNeighborsClassifier(n_neighbors=5,weights='uniform')
# 3rd argument is metric ,default is 'minkowski'
# 4th arg is p(power of minkowski distance), default =2 ,which is eq. to eucledian

clf.fit(X_train,y_train)

prediction = clf.predict(X_test)

print('----------PREDICTIONS----------')
print(prediction)
print('-------------------------------')

print('Accuracy = ',metrics.accuracy_score(y_test, prediction, normalize=True))
print('\nConfusion Matrix = \n',metrics.confusion_matrix(y_test, prediction, normalize=None))

----------PREDICTIONS----------
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
-------------------------------
Accuracy =  0.9866666666666667

Confusion Matrix = 
 [[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]
