In [4]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")


In [6]:
X = np.random.rand(20,2)
perct_class = [0.1,0.3,0.6]
y = np.hstack([[ii] * int(20 * perc)
                for ii, perc in enumerate(perct_class)])


In [7]:
n_splits = 5
cv = KFold(n_splits)

for train_index, test_index in cv.split(X):
    print('Iteration ------------------------ :')
    print(train_index)
    print(test_index)
    print(X[train_index])
    print(X[test_index])


Iteration ------------------------ :
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3]
[[0.30725634 0.22502628]
 [0.08935951 0.11513704]
 [0.98608356 0.83000093]
 [0.16395696 0.84263014]
 [0.26773087 0.82085257]
 [0.54366822 0.84624987]
 [0.57111341 0.8545321 ]
 [0.07106177 0.31467286]
 [0.54894288 0.92212491]
 [0.06017434 0.90193604]
 [0.30449604 0.3370299 ]
 [0.48001355 0.96485754]
 [0.21134289 0.79468731]
 [0.95772903 0.04128629]
 [0.05617449 0.36672539]
 [0.48899483 0.55375563]]
[[0.47207267 0.41670039]
 [0.66369191 0.03677116]
 [0.25931815 0.18083611]
 [0.2417493  0.87439758]]
Iteration ------------------------ :
[ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6 7]
[[0.47207267 0.41670039]
 [0.66369191 0.03677116]
 [0.25931815 0.18083611]
 [0.2417493  0.87439758]
 [0.26773087 0.82085257]
 [0.54366822 0.84624987]
 [0.57111341 0.8545321 ]
 [0.07106177 0.31467286]
 [0.54894288 0.92212491]
 [0.06017434 0.90193604]
 [0.30449604 0.3370299 ]
 [0.48001355 0.96485754]
 [0.

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

n_splits = 5
cv = KFold(n_splits)


KNN = KNeighborsClassifier(n_neighbors=3)
RFC = RandomForestClassifier(n_estimators=50,random_state=1)
LG  = LogisticRegression(random_state=0)

knn_score =[]
rfc_score =[]
lr_score  =[]
for train_index, test_index in cv.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    KNN.fit(X_train,y_train)
    RFC.fit(X_train,y_train)
    LG.fit(X_train,y_train)
    pred_KNN=KNN.predict(X_test)
    pred_RFC=RFC.predict(X_test)
    pred_LG=LG.predict(X_test)
    accur_KNN=accuracy_score(y_test,pred_KNN)
    accur_RFC=accuracy_score(y_test,pred_RFC)
    accur_LG=accuracy_score(y_test,pred_LG)
    print('KNN Accuracy:', accur_KNN)
    print('RFC Accuracy:', accur_RFC)
    print('LR  Accuracy:', accur_LG)
    knn_score.append(accur_KNN)
    rfc_score.append(accur_RFC)
    lr_score.append(accur_LG)

print('Scores for KNN :',knn_score)
print('Mean Score for KNN:',np.mean(knn_score))
print('Scores for RFC :',rfc_score)
print('Mean Score for RFC:',np.mean(rfc_score))
print('Scores for LR :',lr_score)
print('Mean Score for LR:',np.mean(lr_score))


KNN Accuracy: 1.0
RFC Accuracy: 1.0
LR  Accuracy: 1.0
KNN Accuracy: 1.0
RFC Accuracy: 1.0
LR  Accuracy: 1.0
KNN Accuracy: 0.8333333333333334
RFC Accuracy: 0.8666666666666667
LR  Accuracy: 0.8666666666666667
KNN Accuracy: 0.9333333333333333
RFC Accuracy: 0.9333333333333333
LR  Accuracy: 0.9333333333333333
KNN Accuracy: 0.7666666666666667
RFC Accuracy: 0.7333333333333333
LR  Accuracy: 0.8333333333333334
Scores for KNN : [1.0, 1.0, 0.8333333333333334, 0.9333333333333333, 0.7666666666666667]
Mean Score for KNN: 0.9066666666666666
Scores for RFC : [1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]
Mean Score for RFC: 0.9066666666666666
Scores for LR : [1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.8333333333333334]
Mean Score for LR: 0.9266666666666665
